### ISSUE TITLE
Error of "model.predict_generator"

### ISSUE THREAD

**Issue by ycjing** [ypwhs/dogs_vs_cats#3]
Hi, thanks for the great code. It is great for a beginner of Keras, like me. But I found some errors when I run the code. In gap.py, the terminal reports that "AttributeError: 'DirectoryIterator' object has no attribute 'nb_sample'". I wonder if it is due to the different versions of keras and is there any solutions to this? Thanks ahead of time!

**Comment by ypwhs** [comment]
我用的版本是 Keras 1.2.2，你可以用这个命令安装这个版本的Keras:

'pip install keras==1.2.2'

**Comment by ycjing** [comment]
@ypwhs Thanks!

**Comment by syeddanish41** [comment]
Replace nb_sample with samples.

**Comment by elitezhe** [comment]
@syeddanish41  Thanks for your reply. But I find that the `train_generator.samples` return value of 25000, that is number of total pictures.
However, we generate feature by batch, so `predict_generator` will run batch_size times more, this seems make the progress never end.

I tried replace `nb_sample` with `samples//batch_size`, it works.(but cannot generate all the 25000, since the batch size i chose is 16)

**Comment by ArrowLuo** [comment]
@elitezhe Maybe replace `nb_sample` with `total_batches_seen` is a better choice.

**Comment by KUNLI6** [comment]
你好，我运行了下，出现了两个错误    1、OSError: [Errno 22] Invalid argument: 'train2\\cat\\cat.0.jpg'  2、TypeError: Error when checking : data should be a Numpy array, or list/dict of Numpy arrays. Found: None...
没法导出后h5文件？？

**Comment by hook923** [comment]
@elitezhe  replace nb_sample with samples//batch_size+1
